spring:
 application:
  name: mathis
 ai:
   mistralai:
    api-key: ${MISTRAL_AI_APIKEY}
    chat:
     api-key: ${MISTRAL_AI_APIKEY}
   vectorstore:
    pgvector:
     initialize-schema: true	
 datasource:
  url: ${DATASOURCE}
jpa:
 hibernate:
  ddl-auto: update
  show-sql: true
 servlet:
  multipart:
   max-file-size: 50MB
   max-request-size: 50MB
   
telegram:
 bot:
  username: ${TELEGRAM_BOT_USERNAME}
  token: ${TELEGRAM_BOT_TOKEN}

owner:
 name: GIST
 website: https://github.com/gvincenzi/mathis