spring:
 application:
  name: mathis
 ai:
   mistralai:
    api-key: ${MISTRAL_AI_APIKEY}
    chat:
     api-key: ${MISTRAL_AI_APIKEY}
   vectorstore:
    pgvector:
     initialize-schema: true	
 datasource:
  url: ${DATASOURCE}
jpa:
 hibernate:
  ddl-auto: update
  show-sql: true
 servlet:
  multipart:
   max-file-size: 50MB
   max-request-size: 50MB
   
telegram:
 bot:
  active: ${TELEGRAM_BOT_ACTIVE}
  username: ${TELEGRAM_BOT_USERNAME}
  token: ${TELEGRAM_BOT_TOKEN}

owner:
 name: ${MATHIS_OWNER_NAME}
 website: ${MATHIS_OWNER_WEBSITE}
 adminPassword: ${MATHIS_OWNER_ADMIN_PASSWORD}

prompts:
 adminRoleCheckFailed: classpath:/prompts/adminRoleCheckFailed.st
 analysisIntent: classpath:/prompts/analysisIntent.st
 base: classpath:/prompts/base.st
 welcome: classpath:/prompts/welcome.st
 adminNotification: classpath:/prompts/adminNotification.st
 translation: classpath:/prompts/translation.st
 
message:
 LIST_DOCUMENTS_TEXT: List of available documents
 ASK_DOCUMENTS_TEXT: Here are the documents that might interest you (if you ask me, I can give you the complete list of available documents)
 USER_MAIL_SENT_TEXT: Thank you for providing your email. I will keep it in mind for any future communications. If you would like me to have the administrators contact you, just let me know and feel free to write a message youâ€™d like them to receive, in addition to the summary of the conversation that I will send.
 ASK_USER_MAIL_TEXT: To notify my administrator, I need your email address
  
cors:
 allowed-origins:
   - "http://localhost:8000"

server:
 port: 8090
 servlet:
  context-path: /mathis