spring:
 application:
  name: mathis
 ai:
   mistralai:
    api-key: ${MISTRAL_AI_APIKEY}
    chat:
     api-key: ${MISTRAL_AI_APIKEY}
   vectorstore:
    pgvector:
     initialize-schema: true	
 datasource:
  url: ${DATASOURCE}
jpa:
 hibernate:
  ddl-auto: update
  show-sql: true
 servlet:
  multipart:
   max-file-size: 50MB
   max-request-size: 50MB
   
telegram:
 bot:
  active: ${TELEGRAM_BOT_ACTIVE}
  username: ${TELEGRAM_BOT_USERNAME}
  token: ${TELEGRAM_BOT_TOKEN}

owner:
 name: ${MATHIS_OWNER_NAME}
 website: ${MATHIS_OWNER_WEBSITE}
 
message:
 LIST_DOCUMENTS_TEXT: List of available documents
 ASK_DOCUMENTS_TEXT: Here are the documents that might interest you (if you ask me, I can give you the complete list of available documents)